# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48dfc4749b95592843a0e38b30990e272c3644bd78f56cfd40bd4c040e9699af1107a94bd0471e21e7cb4fbba9a02804d737780df98e8b9bb2f6676e2d89ee9d

test:
  secret_key_base: ac3eb4f88ad008edf56d15c560fe295847a0163b7b2f4f09ccc26fbe159165529ff6265ef6830ce939d55d9fbc3382def1e8d2ffd1614bce8befbbc0f2618744

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
